apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: green-
namespace: green
  
bases:
- ../../base
patchesJson6902:
  - target:
      version: v1
      group: apps.openshift.io
      kind: DeploymentConfig
      name: hello
    path: deploymentconfig.yml
  - target:
      version: v1
      group: build.openshift.io
      kind: BuildConfig
      name: hello
    path: buildconfig.yml
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: hello
    path: route.yml
  - target:
      version: v1
      kind: Namespace
      name: hello
    path: namespace.yml

images:
  - name: hello
    newName: green-hello
    newTag: latest
