apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: hello
    app.kubernetes.io/component: hello
    app.kubernetes.io/instance: hello
  name: hello
  namespace: hello
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: hello:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/dmi3mis/hello
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.4-ubi8
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: ohGcPJN_yoohtHjKSiln
    type: GitHub
  - generic:
      secret: xK6olAdfeZ_1OWlB4LGx
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
  